### PR TITLE
update to proto v2

### PR DESCRIPTION
**Pull request by binjip978**

### CODE REVIEW

**Comment by Calebjh** [comment]
I tried to import these changes into the gentool and use it on tagging, and it appeared to create a `Preprocess()` function call for all the WKTs (e.g. Timestamps and UUIDs). I think the check that the type is from the active package isn't working properly with these changes?

**Comment by drewwells** [comment]
> I tried to import these changes into the gentool and use it on tagging, and it appeared to create a `Preprocess()` function call for all the WKTs (e.g. Timestamps and UUIDs). I think the check that the type is from the active package isn't working properly with these changes?

Does this change fix your issue @Calebjh ?

**Comment by Calebjh** [comment]
I've tried it a few different ways, but when I include this branch in the gentool and re-build the `.pb.preprocess.go` in tagging I'm still seeing the unexpected content. Not positive why
```
	if m.CreatedAt != nil {
		m.CreatedAt.Preprocess()
	}

	if m.UpdatedAt != nil {
		m.UpdatedAt.Preprocess()
	}

	if m.DeletedAt != nil {
		m.DeletedAt.Preprocess()
	}
```

**Comment by binjip978** [comment]
yeah I got, the issue happens because I use stupid suffix check, so "google.golang.org/protobuf/types/known/timestamppb" -> pb is treated as type from the same package :)

**Review by Calebjh — APPROVED** [review]
It looks like a few newlines are missing from the generated output, but I think it's working

**Pull request merged**
